name: Build Karaf 4.4.8 

on:
  push:
    paths:
      - '.github/workflows/k448.yml'
  pull_request:
  workflow_dispatch:
    inputs:
      test:
        description: 'Enable OH tests'
        required: false
        default: false
        type: boolean

jobs:
  build-all:
    name: Build OH
    # typical duration is ~15min, set twice the amount as limit (default is 6h)
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Cache
        uses: actions/cache@v4
        with:
          key: k448
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/openhab
            !~/.m2/repository/org/apache/karaf
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Karaf
        run: |
          gh repo clone apache/karaf
          cd karaf
          # use tag if available
          git checkout karaf-4.4.8
          # workaround if tag is not available:
          # git checkout 77426d226d18dbcb74fe40723cad4bd193424489
          # gh pr diff 1983 | git apply
          git branch -v
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Karaf
        run: |
          cd karaf
          mvn install -DskipTests -B -ntp
      - name: Core
        run: |
          gh repo clone holgerfriedrich/openhab-core
          cd openhab-core
          git checkout k448
          git branch -v
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Core
        if: ${{ github.event.inputs.test != 'true' }}
        run: |
          cd openhab-core
          ./mvnw -Dmaven=4.0.0-rc-4 install -Dspotless.check.skip -DskipTests -DskipChecks -T3 -DwithResolver -B -ntp
      - name: Build & Test Core
        if: ${{ github.event.inputs.test == 'true' }}
        run: |
          cd openhab-core
          ./mvnw -Dmaven=4.0.0-rc-4 install -T3 -DwithResolver -B -ntp
      - name: Webui 
        run: |
          gh repo clone holgerfriedrich/openhab-webui
          cd openhab-webui
          git checkout k448
          git branch -v
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Webui
        if: ${{ github.event.inputs.test != 'true' }}
        run: |
          cd openhab-webui
          ./mvnw -Dmaven=4.0.0-rc-4 install -Dspotless.check.skip -DskipTests -DskipChecks -T3 -DwithResolver -B -ntp
      - name: Build & Test Webui
        if: ${{ github.event.inputs.test == 'true' }}
        run: |
          cd openhab-webui
          ./mvnw -Dmaven=4.0.0-rc-4 install -Dspotless.check.skip -DskipTests -DskipChecks -T3 -DwithResolver -B -ntp
      - name: Addons
        run: |
          gh repo clone holgerfriedrich/openhab-addons
          cd openhab-addons
          git checkout k448
          git branch -v
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Addons
        if: ${{ github.event.inputs.test != 'true' }}
        run: |
          cd openhab-addons
          ./mvnw -Dmaven=4.0.0-rc-4 install -Dspotless.check.skip -DskipTests -DskipChecks -T3 -DwithResolver -B -ntp
      - name: Distro 
        if: ${{ github.event.inputs.test == 'true' }}
        run: |
          gh repo clone holgerfriedrich/openhab-distro
          cd openhab-distro
          git checkout k448
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Distro
        if: ${{ github.event.inputs.test != 'true' }}
        run: |
          cd openhab-distro
          ./mvnw -Dmaven=4.0.0-rc-4 install -Dspotless.check.skip -DskipTests -DskipChecks -T3 -DwithResolver -B -ntp
      - name: Build & Test Distro
        if: ${{ github.event.inputs.test == 'true' }}
        run: |
          cd openhab-distro
          ./mvnw -Dmaven=4.0.0-rc-4 install -Dspotless.check.skip -DskipTests -DskipChecks -T3 -DwithResolver -B -ntp
      - name: Upload Core
        uses: actions/upload-artifact@v4
        with:
          name: openhab-core-b${{ github.run_number }}
          path: openhab-distro/distributions/openhab/target/*.zip
          retention-days: 5
      - name: Upload Addons
        uses: actions/upload-artifact@v4
        with:
          name: openhab-addons-b${{ github.run_number }}
          path: openhab-distro/distributions/openhab-addons/target/*.kar
          retention-days: 5
      - name: Show Resover Status 
        run: |
          cd openhab-core
          git branch -v
          git status
          git diff
          cd ..
          cd openhab-webui
          git branch -v
          git status
          git diff
          cd ..
          cd openhab-addons
          git branch -v
          git status
          git diff
          cd ..
          cd openhab-distro
          git branch -v
          git status
          git diff
